modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"


[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "${mod_icon}"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"


[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
